set(MYSQL_INCLUDE_DIR ${CMAKE_CURRENT_LIST_DIR}/include)
set(MYSQL_LIBRARY ${CMAKE_CURRENT_LIST_DIR}/lib/${DEP_ARCH}_release/libmySQL.lib)
set(MYSQL_DEBUG_LIBRARY ${CMAKE_CURRENT_LIST_DIR}/lib/${DEP_ARCH}_debug/libmySQL.lib)
