{
 "title": "vMaNGOS World - Simple",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "realmId",
    "label": "RealmID",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Player Count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "target": "alias(vmangos_metric.$realmId.player.sessionCount, 'sessionCount')"
    }
   ]
  },
  {
   "title": "Tick Time (should be less than 50ms)",
   "type": "timeseries",
   "description": "Should be less than 50ms, see `WORLD_SLEEP_CONST`",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "target": "alias(vmangos_metric.$realmId.world.updateTime.total, 'total')"
    }
   ]
  },
  {
   "title": "Allocated Memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "target": "alias(vmangos_metric.$realmId.server.memAllocatedBytes, 'allocatedMemory')"
    }
   ]
  },
  {
   "title": "Loaded Maps",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "target": "vmangos_metric.$realmId.world.loadedMaps"
    }
   ]
  }
 ]
}