{
 "title": "vMaNGOS World Server Metrics",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   {
    "name": "realmId",
    "label": "RealmID",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Player Count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "target": "alias(vmangos_metric.$realmId.player.sessionCount, 'sessionCount')"
    },
    {
     "target": "alias(vmangos_metric.$realmId.network.socketEvent.newConnection, 'newConnection')"
    },
    {
     "target": "alias(vmangos_metric.$realmId.network.socketEvent.closeConnection, 'closeConnection')"
    }
   ]
  },
  {
   "title": "Tick Time (should be less than 50ms)",
   "type": "timeseries",
   "description": "Should be less than 50ms, see `WORLD_SLEEP_CONST`",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "target": "exclude(aliasByMetric(vmangos_metric.$realmId.world.updateTime.*), 'total')"
    },
    {
     "target": "alias(vmangos_metric.$realmId.world.updateTime.total, 'total')"
    }
   ]
  },
  {
   "title": "Network: Max Time Single Handler Took",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "target": "aliasByNode(vmangos_metric.$realmId.network.packet.processTime.*, 5)"
    }
   ]
  },
  {
   "title": "Network: Traffic",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "target": "alias(sum(vmangos_metric.$realmId.network.packet.recvCount.*, *), 'count(recv)')"
    },
    {
     "target": "alias(sum(vmangos_metric.$realmId.network.packet.sendCount.*, *), 'count(send)')"
    },
    {
     "target": "alias(sum(vmangos_metric.$realmId.network.packet.recvBytes.*, *), 'bytes(recv)')"
    },
    {
     "target": "alias(sum(vmangos_metric.$realmId.network.packet.sendBytes.*, *), 'bytes(send)')"
    }
   ]
  },
  {
   "title": "Allocated Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "target": "alias(vmangos_metric.$realmId.server.memAllocatedBytes, 'allocatedMemory')"
    }
   ]
  },
  {
   "title": "Amount of AsyncUpdate loops (should be >0)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "targets": [
    {
     "target": "vmangos_metric.$realmId.world.update.completeAsyncLoops"
    }
   ]
  },
  {
   "title": "Loaded Maps",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "targets": [
    {
     "target": "vmangos_metric.$realmId.world.loadedMaps"
    }
   ]
  }
 ]
}